server: 
  port: 8081
  servlet:
    context-path: /girl
girl: 
  cupSize: B
  age: 18
  content: "cupSize: ${cupSize}, age: ${age}"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhtdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    view:
      prefix: /
      suffix: .html